/*

 BACKGROUNDFASE1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\filip\Documents\UFS\Projeto_IHS_Adventure\Sprites\backgroundFase1Sprites.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define backgroundFase1Width 20
#define backgroundFase1Height 18
#define backgroundFase1Bank 0

extern unsigned char backgroundFase1[];

/* End of BACKGROUNDFASE1.H */
