/*

 MAINSCREEN.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\filip\Documents\UFS\Projeto_IHS_Adventure\fontMainScreen.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define bgmainscreenWidth 20
#define bgmainscreenHeight 18
#define bgmainscreenBank 0

extern unsigned char bgmainscreen[];

/* End of MAINSCREEN.H */
