/*

 SPRITES.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char sprites[] =
{
  0x08,0x08,0x0C,0x0C,0x0E,0x0E,0xFF,0xFF,
  0xFF,0xFF,0x0E,0x0E,0x0C,0x0C,0x08,0x08
};

/* End of SPRITES.C */
